// react-app/src/tareas/Footer.js
import { useState, useEffect } from 'react'

export function Footer({applyFilter}) {

	const filtros = ['Todas', 'Completas', 'Activas']

	const [filtroActivo, setFiltroActivo] = useState('Todas')
	useEffect(() => {
		setFiltroActivo('Todas')
		document.querySelectorAll('[name="filtros"]')[0].setAttribute('checked', true)
	}, [])

	useEffect(() => {
		applyFilter(filtroActivo)
	}, [filtroActivo])
	
	const onChangeFiltro = (event) => {
		setFiltroActivo(event.target.value)
	}

	const onClickBorrarTodos = () => {
		// modal confirm
	}
	console.log('Filtro', filtroActivo)
	return (
		<div className="footer">
			<div className="filtros">
				<span>
					Filtros: 
				</span>
				<div className="form-check form-check-inline">
					{filtros.map(
						(filtro) => {
							return (
							<label className="form-check-label" key={filtro}>
								<input className="form-check-input"
								type="radio" name="filtros" 
								value={filtro} onChange={onChangeFiltro}/>
								{/* [formControl]="fcFiltro" [value]="filtro"> */}
								<span>{filtro}</span>
							</label>
							)	
						}
					)}

				</div>
				<button type="button" className="btn btn-primary btn-sm" 
					onClick={onClickBorrarTodos}>
					Borrar Todas
				</button>
			</div>

			<template id="confirm" let-modal>
				<div className="modal-header">
					<p>¿Esta seguro de que desea borrar todas las tareas?</p>
				</div>
				<div className="modal-footer">
					<button type="button" className="btn btn-outline-dark" 
						onClick="modal.close('Cancel')">
						Cancelar
					</button>
					<button type="button" className="btn btn-outline-dark" 
						onClick="modal.close('Confirm')">
						Confirmar
					</button>
				</div>
			</template>
		</div>
	)
	
}

// projects/app-tareas/src/app/tareas-base/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormControl } from '@angular/forms';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';
import { Filtros } from '../../models/filtros';
import { TareasService } from '../services/tareas.service';

@Component({
  selector: 'skl-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent implements OnInit {
	filtros!: Array<Filtros>
	fcFiltro!: FormControl
  	constructor(
    	private fb: FormBuilder,
		private tareasService: TareasService,
		private modalService: NgbModal
  ) { }

  ngOnInit(): void {
    this.filtros = [
			Filtros.Todas, Filtros.Completas, Filtros.Activas
		]
		this.fcFiltro = this.fb.control('Todas')

		this.fcFiltro.valueChanges.subscribe(
			value => this.tareasService.setFilter(value)
		)
  }

  onClickBorrarTodos(modalName: any) {
		this.modalService.open(modalName, {
			ariaLabelledBy: 'modal-basic-title',
			backdrop: 'static'
		}).result.then(
			result => {
				if (result == 'Confirm') {
					this.tareasService.deleteAllTareas()
				}
			}
		)
	}

}

<div class="filtros">
    <span>
        Filtros: 
    </span>
    <div class="form-check form-check-inline">
        <label class="form-check-label" *ngFor="let filtro of filtros">
            <input class="form-check-input" [formControl]="fcFiltro"
            type="radio" name="filtros" [value]="filtro"> 
                {{filtro}}
        </label>
    </div>
    <button type="button" class="btn btn-primary btn-sm" (click)="onClickBorrarTodos(confirm)">
        Borrar Todas
    </button>
</div>

<ng-template #confirm let-modal>
    <div class="modal-header">
        <p>¿Esta seguro de que desea borrar todas las tareas?</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-outline-dark" 
            (click)="modal.close('Cancel')">
            Cancelar
        </button>
        <button type="button" class="btn btn-outline-dark" 
            (click)="modal.close('Confirm')">
            Confirmar
        </button>
    </div>
</ng-template>
