// projects/app-tareas/src/app/tareas-base/lista/lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Filtros } from '../../models/filtros';
import { Tarea } from '../../models/tarea.model';
import { TareasService } from '../services/tareas.service';

@Component({
	selector: 'skl-lista',
	templateUrl: './lista.component.html',
	styleUrls: ['./lista.component.scss']
})
export class ListaComponent implements OnInit {
	tareas!: Array<Tarea>

	constructor(
		private tareasService: TareasService
	) {
		
	 }

	ngOnInit(): void {
		this.tareas = []
		this.tareasService.store$.subscribe(
			(data: Array<Tarea>) => this.tareas = data
		);
		this.tareasService.setFilter(Filtros.Todas)
	}
}

<p class="h2">Lista</p>

<skl-nueva></skl-nueva>

<div class="lista">
    <ng-container *ngIf="tareas?.length; else sinTareas" >
        <p class="h4">Lista de tareas</p>
        <ul>
            <!-- <li *ngFor="let tarea of tareas; let i = index"> -->
            <li *ngFor="let item of tareas; index as i">
                <skl-tarea [tarea]="item"></skl-tarea>
            </li>
        </ul>
    </ng-container>
</div>

<div>
    <skl-footer></skl-footer>
</div>

<ng-template #sinTareas>
    <p>Anímate a añadir una tarea</p>
</ng-template>

// react-app/src/tareas/Lista.js

import { Tarea } from "./Tarea";

export function Lista ({tareas, changeTarea, deleteTarea}) {
	/* <ng-container *ngIf="tareas?.length; else sinTareas" >
	/ng-container> */
	if (tareas?.length) {
		return (
			<div className="lista">
				<p className="h4">Lista de tareas</p>
				<ul>
					{/* <li *ngFor="let item of tareas; index as i">
					<skl-tarea [tarea]="item"></skl-tarea>
					</li> */}
					{tareas.map(
						tarea => {
						return (
							<li key={tarea._id}>
								<Tarea  
									tarea={tarea}
									deleteTarea = {deleteTarea}
									changeTarea = {changeTarea}>	
								</Tarea>
							</li>
							)
						}
					)}
				</ul>
			</div>)
	} else {
		return (
			<div className="lista">
				<p>Anímate a añadir una tarea</p>
			</div>)
	}
}
