// projects/app-tareas/src/app/tareas/tarea/tarea.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Tarea } from '../../models/tarea.model';
import { Store } from '@ngrx/store';
import { State } from '../../reducers';
import { ChangeTarea, RemoveTarea } from '../redux/tarea.actions';


@Component({
	selector: 'skl-tarea',
	templateUrl: './tarea.component.html',
	styleUrls: ['./tarea.component.scss']
})
export class TareaComponent implements OnInit {
	@Input() tarea!: Tarea
	@Input() indice!: number
	constructor(private store: Store<State>) {}

	ngOnInit(): void {
		this.tarea = {...this.tarea};
	}

	onChangeCompleted(): void {
		this.store.dispatch(ChangeTarea({payload: this.tarea}))
	}

	onClickBorrar(): void {
		this.store.dispatch(RemoveTarea({payload: this.tarea._id}))
	}

}

<span>
    <input type="checkbox" [(ngModel)]="tarea.isCompleted" 
        (change)="onChangeCompleted()">                    
</span>
<span>{{ tarea._id.slice(0,8) }}</span>
<span [ngClass]="{completed: tarea.isCompleted}"
>{{tarea.titulo}} | {{tarea.responsable}}</span>
<span> {{tarea.fechaInicio | date : 'fullDate'}}</span>
<span class="boton" (click)="onClickBorrar()">🗑</span>

// react-app/src/tareas/Tarea.js
//import { useState } from 'react'

export function Tarea ({tarea, changeTarea, deleteTarea }) {

	//const [completedState, setcompletedState] = useState(tarea.isCompleted)

	const onChangeCompleted = (ev) => {
		//setcompletedState(ev.target.value)
		changeTarea(tarea._id, ev.target.checked)
	}

	const onClickBorrar = () => {
		deleteTarea(tarea._id)
	}


	//const tarea = tarea
	return (
		<div className="tarea">
			<span>
				<input type="checkbox" 
				checked={tarea.isCompleted}
				onChange={onChangeCompleted} />                    
			</span>
			<span>{ tarea?._id.slice(0,8) }</span>
			<span>{tarea?.titulo} | {tarea?.responsable}</span>
			<span> {tarea?.fechaInicio.toLocaleString()}</span>
			<span className="boton" onClick={onClickBorrar}>
				🗑
			</span> 
		</div>
		)

	/* <span>
		<input type="checkbox" [(ngModel)]="tarea.isCompleted" 
			(change)="onChangeCompletedSend()">                    
	</span>
	<span>{{ tarea._id.slice(0,8) }}</span>
	<!-- <span [className.completed]="tarea.isCompleted"
	>{{tarea.titulo}} | {{tarea.responsable}}</span> -->
	<span [ngClass]="{completed: tarea.isCompleted}"
	>{{tarea.titulo}} | {{tarea.responsable}}</span>
	<span> {{tarea.fechaInicio | date : 'fullDate'}}</span>
	<span className="boton" (click)="onClickBorrarSend()">🗑</span> */


}
